.class public Lorg/rajawali3d/loader/LoaderGCode;
.super Lorg/rajawali3d/loader/AMeshLoader;
.source "LoaderGCode.java"


# annotations
.annotation system Ldalvik/annotation/MemberClasses;
    value = {
        Lorg/rajawali3d/loader/LoaderGCode$GCodeLayer;,
        Lorg/rajawali3d/loader/LoaderGCode$GCodeLine;,
        Lorg/rajawali3d/loader/LoaderGCode$SupportedCommands;,
        Lorg/rajawali3d/loader/LoaderGCode$GCodeFlavor;,
        Lorg/rajawali3d/loader/LoaderGCode$GCodeParseException;
    }
.end annotation


# instance fields
.field private metaData:Ljava/util/HashMap;
    .annotation system Ldalvik/annotation/Signature;
        value = {
            "Ljava/util/HashMap<",
            "Ljava/lang/String;",
            "Ljava/lang/String;",
            ">;"
        }
    .end annotation
.end field


# direct methods
.method public constructor <init>(Landroid/content/res/Resources;Lorg/rajawali3d/materials/textures/TextureManager;I)V
    .locals 0

    .line 474
    invoke-direct {p0, p1, p2, p3}, Lorg/rajawali3d/loader/AMeshLoader;-><init>(Landroid/content/res/Resources;Lorg/rajawali3d/materials/textures/TextureManager;I)V

    .line 475
    invoke-virtual {p0}, Lorg/rajawali3d/loader/LoaderGCode;->init()V

    return-void
.end method

.method public constructor <init>(Ljava/io/File;)V
    .locals 0

    .line 459
    invoke-direct {p0, p1}, Lorg/rajawali3d/loader/AMeshLoader;-><init>(Ljava/io/File;)V

    .line 460
    invoke-virtual {p0}, Lorg/rajawali3d/loader/LoaderGCode;->init()V

    return-void
.end method

.method public constructor <init>(Ljava/lang/String;)V
    .locals 0

    .line 454
    invoke-direct {p0, p1}, Lorg/rajawali3d/loader/AMeshLoader;-><init>(Ljava/lang/String;)V

    .line 455
    invoke-virtual {p0}, Lorg/rajawali3d/loader/LoaderGCode;->init()V

    return-void
.end method

.method public constructor <init>(Lorg/rajawali3d/renderer/Renderer;Ljava/io/File;)V
    .locals 0

    .line 464
    invoke-direct {p0, p1, p2}, Lorg/rajawali3d/loader/AMeshLoader;-><init>(Lorg/rajawali3d/renderer/Renderer;Ljava/io/File;)V

    .line 465
    invoke-virtual {p0}, Lorg/rajawali3d/loader/LoaderGCode;->init()V

    return-void
.end method

.method public constructor <init>(Lorg/rajawali3d/renderer/Renderer;Ljava/lang/String;)V
    .locals 0

    .line 469
    invoke-direct {p0, p1, p2}, Lorg/rajawali3d/loader/AMeshLoader;-><init>(Lorg/rajawali3d/renderer/Renderer;Ljava/lang/String;)V

    .line 470
    invoke-virtual {p0}, Lorg/rajawali3d/loader/LoaderGCode;->init()V

    return-void
.end method

.method public static final tasteFlavor(Landroid/content/res/Resources;I)Lorg/rajawali3d/loader/LoaderGCode$GCodeFlavor;
    .locals 1
    .annotation system Ldalvik/annotation/Throws;
        value = {
            Ljava/io/IOException;,
            Landroid/content/res/Resources$NotFoundException;
        }
    .end annotation

    .line 782
    new-instance v0, Ljava/io/BufferedInputStream;

    invoke-virtual {p0, p1}, Landroid/content/res/Resources;->openRawResource(I)Ljava/io/InputStream;

    move-result-object p0

    invoke-direct {v0, p0}, Ljava/io/BufferedInputStream;-><init>(Ljava/io/InputStream;)V

    .line 783
    invoke-static {v0}, Lorg/rajawali3d/loader/LoaderGCode;->tasteFlavor(Ljava/io/BufferedInputStream;)Lorg/rajawali3d/loader/LoaderGCode$GCodeFlavor;

    move-result-object p0

    .line 784
    invoke-virtual {v0}, Ljava/io/BufferedInputStream;->close()V

    return-object p0
.end method

.method public static final tasteFlavor(Ljava/io/BufferedInputStream;)Lorg/rajawali3d/loader/LoaderGCode$GCodeFlavor;
    .locals 4
    .annotation system Ldalvik/annotation/Throws;
        value = {
            Ljava/io/IOException;
        }
    .end annotation

    const/16 v0, 0xc8

    new-array v1, v0, [B

    .line 799
    invoke-virtual {p0, v0}, Ljava/io/BufferedInputStream;->mark(I)V

    const/4 v2, 0x0

    .line 801
    :goto_0
    invoke-virtual {p0}, Ljava/io/BufferedInputStream;->available()I

    move-result v3

    if-lez v3, :cond_0

    if-ge v2, v0, :cond_0

    .line 802
    invoke-virtual {p0}, Ljava/io/BufferedInputStream;->read()I

    move-result v3

    int-to-byte v3, v3

    aput-byte v3, v1, v2

    add-int/lit8 v2, v2, 0x1

    goto :goto_0

    .line 805
    :cond_0
    invoke-virtual {p0}, Ljava/io/BufferedInputStream;->reset()V

    .line 806
    new-instance p0, Ljava/lang/String;

    invoke-direct {p0, v1}, Ljava/lang/String;-><init>([B)V

    sget-object v0, Ljava/util/Locale;->US:Ljava/util/Locale;

    invoke-virtual {p0, v0}, Ljava/lang/String;->toLowerCase(Ljava/util/Locale;)Ljava/lang/String;

    move-result-object p0

    const-string v0, "generated by slic3r"

    .line 808
    invoke-virtual {p0, v0}, Ljava/lang/String;->contains(Ljava/lang/CharSequence;)Z

    move-result v0

    if-eqz v0, :cond_1

    .line 809
    sget-object p0, Lorg/rajawali3d/loader/LoaderGCode$GCodeFlavor;->SLIC3R:Lorg/rajawali3d/loader/LoaderGCode$GCodeFlavor;

    return-object p0

    :cond_1
    const-string v0, "skeinforge"

    .line 810
    invoke-virtual {p0, v0}, Ljava/lang/String;->contains(Ljava/lang/CharSequence;)Z

    move-result p0

    if-eqz p0, :cond_2

    .line 811
    sget-object p0, Lorg/rajawali3d/loader/LoaderGCode$GCodeFlavor;->SKEINFORGE:Lorg/rajawali3d/loader/LoaderGCode$GCodeFlavor;

    return-object p0

    .line 814
    :cond_2
    sget-object p0, Lorg/rajawali3d/loader/LoaderGCode$GCodeFlavor;->UNKNOWN:Lorg/rajawali3d/loader/LoaderGCode$GCodeFlavor;

    return-object p0
.end method

.method public static final tasteFlavor(Ljava/io/File;)Lorg/rajawali3d/loader/LoaderGCode$GCodeFlavor;
    .locals 2
    .annotation system Ldalvik/annotation/Throws;
        value = {
            Ljava/io/IOException;,
            Lorg/rajawali3d/loader/LoaderGCode$GCodeParseException;
        }
    .end annotation

    .line 760
    invoke-virtual {p0}, Ljava/io/File;->exists()Z

    move-result v0

    if-nez v0, :cond_1

    .line 763
    invoke-virtual {p0}, Ljava/io/File;->isFile()Z

    move-result v0

    if-eqz v0, :cond_0

    .line 766
    new-instance v0, Ljava/io/BufferedInputStream;

    new-instance v1, Ljava/io/FileInputStream;

    invoke-direct {v1, p0}, Ljava/io/FileInputStream;-><init>(Ljava/io/File;)V

    invoke-direct {v0, v1}, Ljava/io/BufferedInputStream;-><init>(Ljava/io/InputStream;)V

    .line 767
    invoke-static {v0}, Lorg/rajawali3d/loader/LoaderGCode;->tasteFlavor(Ljava/io/BufferedInputStream;)Lorg/rajawali3d/loader/LoaderGCode$GCodeFlavor;

    move-result-object p0

    .line 768
    invoke-virtual {v0}, Ljava/io/BufferedInputStream;->close()V

    return-object p0

    .line 764
    :cond_0
    new-instance p0, Lorg/rajawali3d/loader/LoaderGCode$GCodeParseException;

    const-string v0, "This is not a file."

    invoke-direct {p0, v0}, Lorg/rajawali3d/loader/LoaderGCode$GCodeParseException;-><init>(Ljava/lang/String;)V

    throw p0

    .line 761
    :cond_1
    new-instance p0, Lorg/rajawali3d/loader/LoaderGCode$GCodeParseException;

    const-string v0, "Passed file does not exist."

    invoke-direct {p0, v0}, Lorg/rajawali3d/loader/LoaderGCode$GCodeParseException;-><init>(Ljava/lang/String;)V

    throw p0
.end method


# virtual methods
.method protected getBufferedInputStream()Ljava/io/BufferedInputStream;
    .locals 1
    .annotation system Ldalvik/annotation/Throws;
        value = {
            Ljava/io/FileNotFoundException;
        }
    .end annotation

    const/16 v0, 0x200

    .line 568
    invoke-super {p0, v0}, Lorg/rajawali3d/loader/AMeshLoader;->getBufferedInputStream(I)Ljava/io/BufferedInputStream;

    move-result-object v0

    return-object v0
.end method

.method public getMetaData()Ljava/util/HashMap;
    .locals 1
    .annotation system Ldalvik/annotation/Signature;
        value = {
            "()",
            "Ljava/util/HashMap<",
            "Ljava/lang/String;",
            "Ljava/lang/String;",
            ">;"
        }
    .end annotation

    iget-object v0, p0, Lorg/rajawali3d/loader/LoaderGCode;->metaData:Ljava/util/HashMap;

    return-object v0
.end method

.method public init()V
    .locals 0

    return-void
.end method

.method public parse()Lorg/rajawali3d/loader/AMeshLoader;
    .locals 3
    .annotation system Ldalvik/annotation/Throws;
        value = {
            Lorg/rajawali3d/loader/ParsingException;
        }
    .end annotation

    .line 519
    invoke-super {p0}, Lorg/rajawali3d/loader/AMeshLoader;->parse()Lorg/rajawali3d/loader/AMeshLoader;

    .line 523
    :try_start_0
    invoke-virtual {p0}, Lorg/rajawali3d/loader/LoaderGCode;->getBufferedInputStream()Ljava/io/BufferedInputStream;

    move-result-object v0

    .line 524
    invoke-static {v0}, Lorg/rajawali3d/loader/LoaderGCode;->tasteFlavor(Ljava/io/BufferedInputStream;)Lorg/rajawali3d/loader/LoaderGCode$GCodeFlavor;

    move-result-object v1

    .line 525
    sget-object v2, Lorg/rajawali3d/loader/LoaderGCode$1;->$SwitchMap$org$rajawali3d$loader$LoaderGCode$GCodeFlavor:[I

    invoke-virtual {v1}, Lorg/rajawali3d/loader/LoaderGCode$GCodeFlavor;->ordinal()I

    move-result v1

    aget v1, v2, v1

    const/4 v2, 0x2

    if-eq v1, v2, :cond_1

    const/4 v2, 0x3

    if-eq v1, v2, :cond_0

    goto :goto_0

    .line 531
    :cond_0
    invoke-virtual {p0, v0}, Lorg/rajawali3d/loader/LoaderGCode;->readSkeinforgeComments(Ljava/io/BufferedInputStream;)Ljava/util/HashMap;

    move-result-object v1

    iput-object v1, p0, Lorg/rajawali3d/loader/LoaderGCode;->metaData:Ljava/util/HashMap;

    .line 532
    invoke-virtual {p0, v0}, Lorg/rajawali3d/loader/LoaderGCode;->readGCode(Ljava/io/BufferedInputStream;)Lorg/rajawali3d/Object3D;

    move-result-object v1

    iput-object v1, p0, Lorg/rajawali3d/loader/LoaderGCode;->mRootObject:Lorg/rajawali3d/Object3D;

    .line 535
    :goto_0
    invoke-virtual {p0, v0}, Lorg/rajawali3d/loader/LoaderGCode;->readGCode(Ljava/io/BufferedInputStream;)Lorg/rajawali3d/Object3D;

    move-result-object v1

    iput-object v1, p0, Lorg/rajawali3d/loader/LoaderGCode;->mRootObject:Lorg/rajawali3d/Object3D;

    goto :goto_1

    .line 527
    :cond_1
    invoke-virtual {p0, v0}, Lorg/rajawali3d/loader/LoaderGCode;->readSlic3rComments(Ljava/io/BufferedInputStream;)Ljava/util/HashMap;

    move-result-object v1

    iput-object v1, p0, Lorg/rajawali3d/loader/LoaderGCode;->metaData:Ljava/util/HashMap;

    .line 528
    invoke-virtual {p0, v0}, Lorg/rajawali3d/loader/LoaderGCode;->readGCode(Ljava/io/BufferedInputStream;)Lorg/rajawali3d/Object3D;

    move-result-object v1

    iput-object v1, p0, Lorg/rajawali3d/loader/LoaderGCode;->mRootObject:Lorg/rajawali3d/Object3D;

    :goto_1
    if-eqz v0, :cond_2

    .line 540
    invoke-virtual {v0}, Ljava/io/BufferedInputStream;->close()V
    :try_end_0
    .catch Ljava/io/FileNotFoundException; {:try_start_0 .. :try_end_0} :catch_3
    .catch Ljava/lang/NumberFormatException; {:try_start_0 .. :try_end_0} :catch_2
    .catch Ljava/io/IOException; {:try_start_0 .. :try_end_0} :catch_1
    .catch Ljava/lang/Exception; {:try_start_0 .. :try_end_0} :catch_0

    :cond_2
    return-object p0

    :catch_0
    move-exception v0

    .line 553
    invoke-static {v0}, Landroid/util/Log;->getStackTraceString(Ljava/lang/Throwable;)Ljava/lang/String;

    move-result-object v1

    invoke-static {v1}, Lorg/rajawali3d/util/RajLog;->e(Ljava/lang/String;)V

    .line 554
    new-instance v1, Lorg/rajawali3d/loader/ParsingException;

    const-string v2, "Unexpected exception occured."

    invoke-direct {v1, v2, v0}, Lorg/rajawali3d/loader/ParsingException;-><init>(Ljava/lang/String;Ljava/lang/Throwable;)V

    throw v1

    :catch_1
    move-exception v0

    .line 550
    invoke-static {v0}, Landroid/util/Log;->getStackTraceString(Ljava/lang/Throwable;)Ljava/lang/String;

    move-result-object v1

    invoke-static {v1}, Lorg/rajawali3d/util/RajLog;->e(Ljava/lang/String;)V

    .line 551
    new-instance v1, Lorg/rajawali3d/loader/ParsingException;

    const-string v2, "File reading failed."

    invoke-direct {v1, v2, v0}, Lorg/rajawali3d/loader/ParsingException;-><init>(Ljava/lang/String;Ljava/lang/Throwable;)V

    throw v1

    :catch_2
    move-exception v0

    .line 547
    invoke-static {v0}, Landroid/util/Log;->getStackTraceString(Ljava/lang/Throwable;)Ljava/lang/String;

    move-result-object v1

    invoke-static {v1}, Lorg/rajawali3d/util/RajLog;->e(Ljava/lang/String;)V

    .line 548
    new-instance v1, Lorg/rajawali3d/loader/ParsingException;

    const-string v2, "Unexpected value."

    invoke-direct {v1, v2, v0}, Lorg/rajawali3d/loader/ParsingException;-><init>(Ljava/lang/String;Ljava/lang/Throwable;)V

    throw v1

    :catch_3
    move-exception v0

    .line 543
    new-instance v1, Ljava/lang/StringBuilder;

    const-string v2, "["

    invoke-direct {v1, v2}, Ljava/lang/StringBuilder;-><init>(Ljava/lang/String;)V

    invoke-virtual {p0}, Ljava/lang/Object;->getClass()Ljava/lang/Class;

    move-result-object v2

    invoke-virtual {v2}, Ljava/lang/Class;->getCanonicalName()Ljava/lang/String;

    move-result-object v2

    invoke-virtual {v1, v2}, Ljava/lang/StringBuilder;->append(Ljava/lang/String;)Ljava/lang/StringBuilder;

    const-string v2, "] Could not find file."

    .line 544
    invoke-virtual {v1, v2}, Ljava/lang/StringBuilder;->append(Ljava/lang/String;)Ljava/lang/StringBuilder;

    invoke-virtual {v1}, Ljava/lang/StringBuilder;->toString()Ljava/lang/String;

    move-result-object v1

    .line 543
    invoke-static {v1}, Lorg/rajawali3d/util/RajLog;->e(Ljava/lang/String;)V

    .line 545
    new-instance v1, Lorg/rajawali3d/loader/ParsingException;

    const-string v2, "File not found."

    invoke-direct {v1, v2, v0}, Lorg/rajawali3d/loader/ParsingException;-><init>(Ljava/lang/String;Ljava/lang/Throwable;)V

    throw v1
.end method

.method public bridge synthetic parse()Lorg/rajawali3d/loader/ILoader;
    .locals 1
    .annotation system Ldalvik/annotation/Throws;
        value = {
            Lorg/rajawali3d/loader/ParsingException;
        }
    .end annotation

    .line 40
    invoke-virtual {p0}, Lorg/rajawali3d/loader/LoaderGCode;->parse()Lorg/rajawali3d/loader/AMeshLoader;

    move-result-object v0

    return-object v0
.end method

.method protected readGCode(Ljava/io/BufferedInputStream;)Lorg/rajawali3d/Object3D;
    .locals 25
    .annotation system Ldalvik/annotation/Throws;
        value = {
            Ljava/io/IOException;
        }
    .end annotation

    const-string v0, "GCodePaser: reading file"

    .line 623
    invoke-static {v0}, Lorg/rajawali3d/util/RajLog;->i(Ljava/lang/String;)V

    .line 624
    new-instance v0, Lorg/rajawali3d/Object3D;

    invoke-direct {v0}, Lorg/rajawali3d/Object3D;-><init>()V

    .line 629
    new-instance v1, Lorg/rajawali3d/loader/LoaderGCode$GCodeLayer;

    invoke-direct {v1}, Lorg/rajawali3d/loader/LoaderGCode$GCodeLayer;-><init>()V

    .line 634
    new-instance v2, Lorg/rajawali3d/loader/LoaderGCode$GCodeLine;

    invoke-direct {v2}, Lorg/rajawali3d/loader/LoaderGCode$GCodeLine;-><init>()V

    const/4 v3, 0x0

    .line 635
    invoke-virtual {v2, v3}, Lorg/rajawali3d/loader/LoaderGCode$GCodeLine;->setX(F)V

    .line 636
    invoke-virtual {v2, v3}, Lorg/rajawali3d/loader/LoaderGCode$GCodeLine;->setY(F)V

    .line 637
    invoke-virtual {v2, v3}, Lorg/rajawali3d/loader/LoaderGCode$GCodeLine;->setZ(F)V

    .line 638
    invoke-virtual {v2, v3}, Lorg/rajawali3d/loader/LoaderGCode$GCodeLine;->setE(F)V

    .line 639
    invoke-virtual {v2, v3}, Lorg/rajawali3d/loader/LoaderGCode$GCodeLine;->setF(F)V

    .line 640
    new-instance v4, Ljava/lang/StringBuilder;

    const/16 v5, 0x400

    invoke-direct {v4, v5}, Ljava/lang/StringBuilder;-><init>(I)V

    const/4 v5, 0x0

    move v6, v3

    move v8, v6

    move v7, v5

    .line 642
    :goto_0
    invoke-virtual/range {p1 .. p1}, Ljava/io/BufferedInputStream;->available()I

    move-result v9

    if-lez v9, :cond_14

    .line 643
    invoke-virtual/range {p1 .. p1}, Ljava/io/BufferedInputStream;->read()I

    move-result v9

    int-to-byte v9, v9

    const/16 v10, 0xa

    if-eq v9, v10, :cond_1

    int-to-char v9, v9

    .line 645
    invoke-virtual {v4, v9}, Ljava/lang/StringBuilder;->append(C)Ljava/lang/StringBuilder;

    :cond_0
    :goto_1
    move-object/from16 v22, v4

    :goto_2
    move v4, v3

    goto/16 :goto_8

    .line 648
    :cond_1
    invoke-virtual {v4}, Ljava/lang/StringBuilder;->toString()Ljava/lang/String;

    move-result-object v9

    .line 649
    invoke-virtual {v4}, Ljava/lang/StringBuilder;->length()I

    move-result v10

    invoke-virtual {v4, v5, v10}, Ljava/lang/StringBuilder;->delete(II)Ljava/lang/StringBuilder;

    const-string v10, ";"

    .line 652
    invoke-virtual {v9, v10}, Ljava/lang/String;->startsWith(Ljava/lang/String;)Z

    move-result v10

    if-eqz v10, :cond_2

    goto :goto_1

    :cond_2
    const-string v10, " "

    .line 655
    invoke-virtual {v9, v10}, Ljava/lang/String;->split(Ljava/lang/String;)[Ljava/lang/String;

    move-result-object v10

    if-eqz v10, :cond_0

    .line 656
    array-length v11, v10

    if-nez v11, :cond_3

    goto :goto_1

    .line 660
    :cond_3
    :try_start_0
    aget-object v11, v10, v5

    invoke-static {v11}, Lorg/rajawali3d/loader/LoaderGCode$SupportedCommands;->fromString(Ljava/lang/String;)Lorg/rajawali3d/loader/LoaderGCode$SupportedCommands;

    move-result-object v10
    :try_end_0
    .catch Ljava/lang/IllegalArgumentException; {:try_start_0 .. :try_end_0} :catch_0

    .line 665
    sget-object v11, Lorg/rajawali3d/loader/LoaderGCode$1;->$SwitchMap$org$rajawali3d$loader$LoaderGCode$SupportedCommands:[I

    invoke-virtual {v10}, Lorg/rajawali3d/loader/LoaderGCode$SupportedCommands;->ordinal()I

    move-result v10

    aget v10, v11, v10

    const/4 v11, 0x1

    const/high16 v12, 0x3f800000    # 1.0f

    if-eq v10, v11, :cond_b

    const/4 v13, 0x3

    if-eq v10, v13, :cond_a

    const/4 v13, 0x4

    if-eq v10, v13, :cond_9

    const/4 v11, 0x5

    if-eq v10, v11, :cond_4

    goto :goto_3

    .line 723
    :cond_4
    new-instance v10, Lorg/rajawali3d/loader/LoaderGCode$GCodeLine;

    invoke-direct {v10, v9}, Lorg/rajawali3d/loader/LoaderGCode$GCodeLine;-><init>(Ljava/lang/String;)V

    .line 724
    invoke-virtual {v10}, Lorg/rajawali3d/loader/LoaderGCode$GCodeLine;->getX()F

    move-result v9

    cmpl-float v9, v9, v12

    if-eqz v9, :cond_5

    .line 725
    invoke-virtual {v10}, Lorg/rajawali3d/loader/LoaderGCode$GCodeLine;->getX()F

    move-result v9

    invoke-virtual {v2, v9}, Lorg/rajawali3d/loader/LoaderGCode$GCodeLine;->setX(F)V

    .line 727
    :cond_5
    invoke-virtual {v10}, Lorg/rajawali3d/loader/LoaderGCode$GCodeLine;->getY()F

    move-result v9

    cmpl-float v9, v9, v12

    if-eqz v9, :cond_6

    .line 728
    invoke-virtual {v10}, Lorg/rajawali3d/loader/LoaderGCode$GCodeLine;->getY()F

    move-result v9

    invoke-virtual {v2, v9}, Lorg/rajawali3d/loader/LoaderGCode$GCodeLine;->setY(F)V

    .line 730
    :cond_6
    invoke-virtual {v10}, Lorg/rajawali3d/loader/LoaderGCode$GCodeLine;->getZ()F

    move-result v9

    cmpl-float v9, v9, v12

    if-eqz v9, :cond_7

    .line 731
    invoke-virtual {v10}, Lorg/rajawali3d/loader/LoaderGCode$GCodeLine;->getZ()F

    move-result v9

    invoke-virtual {v2, v9}, Lorg/rajawali3d/loader/LoaderGCode$GCodeLine;->setZ(F)V

    .line 733
    :cond_7
    invoke-virtual {v10}, Lorg/rajawali3d/loader/LoaderGCode$GCodeLine;->getE()F

    move-result v9

    cmpl-float v9, v9, v12

    if-eqz v9, :cond_8

    .line 734
    invoke-virtual {v10}, Lorg/rajawali3d/loader/LoaderGCode$GCodeLine;->getE()F

    move-result v9

    invoke-virtual {v2, v9}, Lorg/rajawali3d/loader/LoaderGCode$GCodeLine;->setE(F)V

    :cond_8
    :goto_3
    move-object/from16 v22, v4

    goto/16 :goto_2

    :cond_9
    move-object/from16 v22, v4

    move v7, v11

    goto/16 :goto_2

    :cond_a
    move-object/from16 v22, v4

    move v7, v5

    goto/16 :goto_2

    .line 667
    :cond_b
    new-instance v10, Lorg/rajawali3d/loader/LoaderGCode$GCodeLine;

    invoke-direct {v10, v9}, Lorg/rajawali3d/loader/LoaderGCode$GCodeLine;-><init>(Ljava/lang/String;)V

    .line 668
    invoke-virtual {v10, v2}, Lorg/rajawali3d/loader/LoaderGCode$GCodeLine;->setOrigin(Lorg/rajawali3d/loader/LoaderGCode$GCodeLine;)V

    .line 670
    invoke-virtual {v10}, Lorg/rajawali3d/loader/LoaderGCode$GCodeLine;->getX()F

    move-result v9

    const/high16 v11, -0x40800000    # -1.0f

    cmpl-float v9, v9, v11

    if-nez v9, :cond_c

    invoke-virtual {v10}, Lorg/rajawali3d/loader/LoaderGCode$GCodeLine;->getY()F

    move-result v9

    cmpl-float v9, v9, v11

    if-nez v9, :cond_c

    invoke-virtual {v10}, Lorg/rajawali3d/loader/LoaderGCode$GCodeLine;->getZ()F

    move-result v9

    cmpl-float v9, v9, v11

    if-nez v9, :cond_c

    goto/16 :goto_1

    .line 674
    :cond_c
    invoke-virtual {v10}, Lorg/rajawali3d/loader/LoaderGCode$GCodeLine;->getX()F

    move-result v9

    cmpl-float v9, v9, v11

    if-nez v9, :cond_d

    move v9, v3

    goto :goto_4

    :cond_d
    invoke-virtual {v10}, Lorg/rajawali3d/loader/LoaderGCode$GCodeLine;->getX()F

    move-result v9

    .line 675
    :goto_4
    invoke-virtual {v10}, Lorg/rajawali3d/loader/LoaderGCode$GCodeLine;->getY()F

    move-result v13

    cmpl-float v13, v13, v11

    if-nez v13, :cond_e

    move v13, v3

    goto :goto_5

    :cond_e
    invoke-virtual {v10}, Lorg/rajawali3d/loader/LoaderGCode$GCodeLine;->getY()F

    move-result v13

    .line 676
    :goto_5
    invoke-virtual {v10}, Lorg/rajawali3d/loader/LoaderGCode$GCodeLine;->getZ()F

    move-result v14

    cmpl-float v14, v14, v11

    if-eqz v14, :cond_f

    .line 677
    invoke-virtual {v10}, Lorg/rajawali3d/loader/LoaderGCode$GCodeLine;->getZ()F

    move-result v6

    cmpl-float v14, v9, v3

    if-nez v14, :cond_f

    cmpl-float v14, v13, v3

    if-nez v14, :cond_f

    goto/16 :goto_0

    .line 682
    :cond_f
    invoke-virtual {v1}, Lorg/rajawali3d/loader/LoaderGCode$GCodeLayer;->getPoints()Ljava/util/Stack;

    move-result-object v14

    new-instance v15, Lorg/rajawali3d/math/vector/Vector3;

    move-object/from16 v22, v4

    float-to-double v3, v9

    float-to-double v12, v13

    move-object/from16 v23, v10

    float-to-double v9, v6

    move-object/from16 v24, v15

    move-wide/from16 v16, v3

    move-wide/from16 v18, v12

    move-wide/from16 v20, v9

    invoke-direct/range {v15 .. v21}, Lorg/rajawali3d/math/vector/Vector3;-><init>(DDD)V

    move-object/from16 v3, v24

    invoke-virtual {v14, v3}, Ljava/util/Stack;->add(Ljava/lang/Object;)Z

    .line 683
    invoke-virtual/range {v23 .. v23}, Lorg/rajawali3d/loader/LoaderGCode$GCodeLine;->getE()F

    move-result v3

    cmpl-float v3, v3, v11

    if-eqz v3, :cond_12

    if-eqz v7, :cond_10

    .line 686
    invoke-virtual/range {v23 .. v23}, Lorg/rajawali3d/loader/LoaderGCode$GCodeLine;->getE()F

    move-result v3

    invoke-virtual {v2}, Lorg/rajawali3d/loader/LoaderGCode$GCodeLine;->getE()F

    move-result v2

    sub-float/2addr v3, v2

    goto :goto_6

    .line 688
    :cond_10
    invoke-virtual/range {v23 .. v23}, Lorg/rajawali3d/loader/LoaderGCode$GCodeLine;->getE()F

    move-result v3

    cmpl-float v2, v3, v11

    if-nez v2, :cond_11

    const/4 v3, 0x0

    :cond_11
    :goto_6
    const/4 v4, 0x0

    cmpl-float v2, v3, v4

    if-lez v2, :cond_13

    cmpl-float v2, v6, v8

    if-lez v2, :cond_13

    .line 698
    new-instance v2, Lorg/rajawali3d/primitives/Line3D;

    invoke-virtual {v1}, Lorg/rajawali3d/loader/LoaderGCode$GCodeLayer;->getPoints()Ljava/util/Stack;

    move-result-object v1

    const/16 v3, 0x11

    const/16 v8, 0xef

    const/16 v9, 0xff

    const/16 v10, 0x55

    invoke-static {v9, v10, v3, v8}, Landroid/graphics/Color;->argb(IIII)I

    move-result v3

    const/high16 v8, 0x3f800000    # 1.0f

    invoke-direct {v2, v1, v8, v3}, Lorg/rajawali3d/primitives/Line3D;-><init>(Ljava/util/Stack;FI)V

    invoke-virtual {v0, v2}, Lorg/rajawali3d/Object3D;->addChild(Lorg/rajawali3d/Object3D;)V

    .line 699
    new-instance v1, Lorg/rajawali3d/loader/LoaderGCode$GCodeLayer;

    invoke-direct {v1}, Lorg/rajawali3d/loader/LoaderGCode$GCodeLayer;-><init>()V

    move v8, v6

    goto :goto_7

    :cond_12
    const/4 v4, 0x0

    :cond_13
    :goto_7
    move-object/from16 v2, v23

    goto :goto_8

    :catch_0
    move-object/from16 v22, v4

    move v4, v3

    .line 662
    new-instance v3, Ljava/lang/StringBuilder;

    const-string v9, "encountered unsupported gcode:"

    invoke-direct {v3, v9}, Ljava/lang/StringBuilder;-><init>(Ljava/lang/String;)V

    aget-object v9, v10, v5

    invoke-virtual {v3, v9}, Ljava/lang/StringBuilder;->append(Ljava/lang/String;)Ljava/lang/StringBuilder;

    invoke-virtual {v3}, Ljava/lang/StringBuilder;->toString()Ljava/lang/String;

    move-result-object v3

    invoke-static {v3}, Lorg/rajawali3d/util/RajLog;->w(Ljava/lang/String;)V

    :goto_8
    move v3, v4

    move-object/from16 v4, v22

    goto/16 :goto_0

    :cond_14
    return-object v0
.end method

.method protected readSkeinforgeComments(Ljava/io/BufferedInputStream;)Ljava/util/HashMap;
    .locals 0
    .annotation system Ldalvik/annotation/Signature;
        value = {
            "(",
            "Ljava/io/BufferedInputStream;",
            ")",
            "Ljava/util/HashMap<",
            "Ljava/lang/String;",
            "Ljava/lang/String;",
            ">;"
        }
    .end annotation

    .annotation system Ldalvik/annotation/Throws;
        value = {
            Ljava/io/IOException;
        }
    .end annotation

    .line 614
    new-instance p1, Ljava/util/HashMap;

    invoke-direct {p1}, Ljava/util/HashMap;-><init>()V

    return-object p1
.end method

.method protected readSlic3rComments(Ljava/io/BufferedInputStream;)Ljava/util/HashMap;
    .locals 9
    .annotation system Ldalvik/annotation/Signature;
        value = {
            "(",
            "Ljava/io/BufferedInputStream;",
            ")",
            "Ljava/util/HashMap<",
            "Ljava/lang/String;",
            "Ljava/lang/String;",
            ">;"
        }
    .end annotation

    .annotation system Ldalvik/annotation/Throws;
        value = {
            Ljava/io/IOException;
        }
    .end annotation

    const/16 v0, 0x1000

    .line 577
    invoke-virtual {p1, v0}, Ljava/io/BufferedInputStream;->mark(I)V

    .line 578
    new-instance v1, Ljava/util/HashMap;

    invoke-direct {v1}, Ljava/util/HashMap;-><init>()V

    .line 580
    new-instance v2, Ljava/lang/StringBuilder;

    const/16 v3, 0x400

    invoke-direct {v2, v3}, Ljava/lang/StringBuilder;-><init>(I)V

    const/4 v3, 0x0

    move v4, v3

    .line 582
    :goto_0
    invoke-virtual {p1}, Ljava/io/BufferedInputStream;->available()I

    move-result v5

    if-lez v5, :cond_4

    if-ge v4, v0, :cond_4

    .line 583
    invoke-virtual {p1}, Ljava/io/BufferedInputStream;->read()I

    move-result v5

    int-to-byte v5, v5

    add-int/lit8 v4, v4, 0x1

    const/16 v6, 0xa

    if-eq v5, v6, :cond_0

    int-to-char v5, v5

    .line 586
    invoke-virtual {v2, v5}, Ljava/lang/StringBuilder;->append(C)Ljava/lang/StringBuilder;

    goto :goto_0

    .line 589
    :cond_0
    invoke-virtual {v2}, Ljava/lang/StringBuilder;->toString()Ljava/lang/String;

    move-result-object v5

    .line 590
    invoke-virtual {v2}, Ljava/lang/StringBuilder;->length()I

    move-result v6

    const/4 v7, 0x1

    if-lez v6, :cond_1

    invoke-virtual {v2}, Ljava/lang/StringBuilder;->length()I

    move-result v6

    sub-int/2addr v6, v7

    goto :goto_1

    :cond_1
    move v6, v3

    :goto_1
    invoke-virtual {v2, v3, v6}, Ljava/lang/StringBuilder;->delete(II)Ljava/lang/StringBuilder;

    const-string v6, ";"

    .line 592
    invoke-virtual {v5, v6}, Ljava/lang/String;->startsWith(Ljava/lang/String;)Z

    move-result v6

    if-nez v6, :cond_2

    goto :goto_2

    :cond_2
    const-string v6, "="

    .line 595
    invoke-virtual {v5, v6}, Ljava/lang/String;->split(Ljava/lang/String;)[Ljava/lang/String;

    move-result-object v5

    .line 596
    array-length v6, v5

    const/4 v8, 0x2

    if-ge v6, v8, :cond_3

    goto :goto_0

    .line 599
    :cond_3
    aget-object v6, v5, v3

    invoke-virtual {v6}, Ljava/lang/String;->trim()Ljava/lang/String;

    move-result-object v6

    .line 600
    aget-object v5, v5, v7

    invoke-virtual {v5}, Ljava/lang/String;->trim()Ljava/lang/String;

    move-result-object v5

    .line 601
    invoke-virtual {v1, v6, v5}, Ljava/util/HashMap;->put(Ljava/lang/Object;Ljava/lang/Object;)Ljava/lang/Object;

    goto :goto_0

    .line 603
    :cond_4
    :goto_2
    invoke-virtual {p1}, Ljava/io/BufferedInputStream;->reset()V

    return-object v1
.end method

.method public setMetaData(Ljava/util/HashMap;)V
    .locals 0
    .annotation system Ldalvik/annotation/Signature;
        value = {
            "(",
            "Ljava/util/HashMap<",
            "Ljava/lang/String;",
            "Ljava/lang/String;",
            ">;)V"
        }
    .end annotation

    iput-object p1, p0, Lorg/rajawali3d/loader/LoaderGCode;->metaData:Ljava/util/HashMap;

    return-void
.end method
